# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da70953d43d18246025ccaa208586bd73d12cba40bf5a1d37e4f9c25aad160481cb0b00898d01ef94a4d965b78992bdabfde51a55472972f17b46228ed958eaa

test:
  secret_key_base: 48dfc2cfcd425573ff539b8006bce3f65e68afcd3b330d2832cf7de978c7912daae84976fe30ba127349b2bb8d831b5bba1bfb198e30e27661cde93881e3612c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
